services:
  backend:
    # Backend Stuff
    container_name: backend
    build:
      context: packages/backend
      dockerfile: ./Dockerfile

    ports:
      - '4000:4000'

    # Network Bridge
    networks:
      - docker-network

    # Environment Variables
    env_file:
      - .env

    volumes:
      - ./config.yaml:/backend/config.yaml

  frontend:
    # Frontend Stuff
    container_name: frontend
    build:
      context: packages/frontend
      dockerfile: ./Dockerfile

    ports:
      - '3000:3000'

    # Network Bridge
    networks:
      - docker-network
    
    # Environment Variables
    env_file:
      - .env

  router:
    # Router Stuff (caddy)
    container_name: router
    build:
      context: packages/router
      dockerfile: ./Dockerfile

    environment:
      - APP_DOMAIN=${APP_DOMAIN}
    
    ports:
     - "80:80"
     - "443:443"

    # Network Bridge
    networks:
      - docker-network
    
    # Environment Variables
    env_file:
      - .env

  database:
    image: mongo
    container_name: database
    ports:
      - "27017:27017"
    volumes:
      - "mongodb_data:/data/db"
      - ./packages/database/mongo.conf:/etc/mongo/mongo.conf:rw
    networks:
      - docker-network
    command: 
      - '--logpath'
      - '/var/log/mongodb/mongod.log'
      - '--config'
      - '/etc/mongo/mongo.conf'

volumes:
  mongodb_data:
    driver: local

networks:
  docker-network:
    driver: bridge