app_domain: "127.0.0.1.nip.io"

backend:
  uvicorn_config:
    # Backend Port, Don't mess with this unless you plan on re-doing the docker config
    port: 4000 

    # Host ip address for backend, also don't mess with ths
    host: "0.0.0.0"

    # Prevent logging
    log_level: "error"
  
  database:

    # For development, this doesn't need to be changed, but for prod, be careful :)
    uri: "mongodb://database.{$APP_DOMAIN}"

  # Email sending settings
  email:
    hostname: "smtp.gmail.com"
    port: 587
    start_tls: true
    username: "username"
    password: "password"
    