services:
  frontend:
    # Frontend Stuff
    build:
      context: packages/frontend
      dockerfile: ./Dockerfile.dev

    volumes:
      - ./packages/frontend:/frontend

  backend:
    # Backend Stuff
    build:
      context: packages/backend
      dockerfile: ./Dockerfile.dev

    volumes:
      - ./packages/backend:/backend
      - ./config.yml:/backend/config.yml


  # Mongo Database Developer
  database:
    volumes:
      - ./packages/database/dev.mongo.conf:/etc/mongo/mongo.conf:rw # Insecure DEV ONLY

   

networks:
  docker-network:
    driver: bridge
