services:
  frontend:
    # Frontend Stuff
    build:
      context: packages/frontend
      dockerfile: ./Dockerfile.dev

    volumes:
      - ./packages/frontend:/frontend

  backend:
    # Backend Stuff
    build:
      context: packages/backend
      dockerfile: ./Dockerfile.dev

    volumes:
      - ./packages/backend:/backend
      - ./config.yml:/backend/config.yml

  nodered:
    image: nodered/node-red:latest
    container_name: nodered
    ports:
      - "1880:1880"
    volumes:
      - ./packages/nodered:/data

    # Network Bridge
    networks:
      - docker-network

    restart: unless-stopped
    

  # Mongo Database Developer
  database:
    volumes:
      - ./packages/database/dev.mongo.conf:/etc/mongo/mongo.conf:rw # Insecure DEV ONLY

  express:
    container_name: express
    image: mongo-express
    restart: always
    ports:
      - 8081:8081    
    environment:
      ME_CONFIG_MONGODB_URL: mongodb://database
      ME_CONFIG_BASICAUTH: false
    networks:
      - docker-network

networks:
  docker-network:
    driver: bridge
