<script lang="ts">
	import Dark from '~icons/ic/round-dark-mode';
	import Light from '~icons/ic/round-light-mode';
	import { Flex } from 'sk-clib';
	import { Dropdown } from '@components';
	import { global_mode$ } from './mode';
	import { type Writable } from 'svelte/store';
	export let className: string = '';

	let mode$: Writable<'dark' | 'light' | string> = global_mode$.mode$;

	const setMode = (mode: 'dark' | 'light') => {
		if (localStorage.getItem("mode") !== mode) global_mode$.toggle();
	};
</script>

<Dropdown.Menu class={className}>
	<Dropdown.Trigger>
		<Dropdown.Button class="w-fit rounded-md">Theme</Dropdown.Button>
	</Dropdown.Trigger>

	<Dropdown.Content class="w-36">
		<Dropdown.Button onclick={() => setMode('light')}>
			<Flex class="items-center pl-6 gap-1">
				<Light />
                Light
			</Flex>
		</Dropdown.Button>

		<Dropdown.Divider/>

		<Dropdown.Button onclick={() => setMode('dark')}>
			<Flex class="items-center pl-6 gap-1">
				<Dark/>
                Dark
			</Flex>
		</Dropdown.Button>
	</Dropdown.Content>
</Dropdown.Menu>

<!--@component
    Created by Amaan Dhanani
    - Uses the `Dropdown` component generated by SvelteForge🔥 (imported through `"src/lib/components"`)
    - Depends on `"./mode.ts"` developed by GitHub user TreltaSev
    - Subject to changes based on future updates by TreltaSev

    @file LightDark.svelte
    @description
    A dropdown menu for toggling between light and dark mode using Tailwind CSS.
    The component is styled using contextual classes from the `Dropdown` component.

    @props
    - `className`: Additional Tailwind utility classes passed in.

    @rendered
    Renders a dropdown that allows switching between light and dark themes.

    @usage

    ```svelte
    <LightDark className="px-10" />
    ```
-->