<script lang="ts">

    // --- Logic ---
    import { cn } from '@lib/utils';
    import type { ButtonProps } from ".."
	import { Button } from 'sk-clib';
	import { getDropdownCtx } from '../ctx.svelte';
    
    let {
        children,
        class: className,
        buttonClass = $bindable(''),
        href = $bindable(undefined),
        onclick = $bindable(() => {}),
        ...rest
    }: ButtonProps = $props();

    // --- Context ---
    const {_class} = getDropdownCtx()

    function route_to() {
        if (!href) return;
        window.location.href = href
    }

    $effect(() => {
        if (href) {
            onclick = route_to
        }
    })


    // Setup Button's class
    let buttonCls = $state(cn(buttonClass, _class.buttonClass, className));
    $effect(() => {
        buttonCls = cn(buttonClass, _class.buttonClass, className)
    })

</script>

<Button class={ buttonCls } {...rest} {onclick}>
    {@render children?.()}
</Button>

<!--@component
    Generated by SvelteForge🔥
-->

