<script lang="ts">

    // --- Logic ---
    import { cn } from '@lib/utils';
    import type { Props } from ".."
	import { setDropdownCtx } from '../ctx.svelte';
    
    let {
        children,
        class: className,
        dropdownClass = $bindable(''),
        buttonClass = $bindable('px-4 py-2 bg-white text-sm font-medium'),
        ...rest
    }: Props = $props();


    // Setup Dropdown's class
    let dropdownCls = $state(cn(dropdownClass, className));
    $effect(() => {
        dropdownCls = cn(dropdownClass, className)
    })

    // Set Context Here
    const {_class} = setDropdownCtx()

    // Populate button class down
    $effect(() => {
        _class.buttonClass = buttonClass
    })

</script>

<div class={ dropdownCls } {...rest}>
    {@render children?.()}
</div>

<!--@component
    Generated by SvelteForge🔥
-->

