<script lang="ts">

    // --- Logic ---
    import { cn } from '@lib/utils';
    import type { DividerProps } from ".."
    
    let {
        children,
        class: className,
        dividerClass = $bindable('')
    }: DividerProps = $props();


    // Setup Divider's class
    let dividerCls = $state(cn(dividerClass, className));
    $effect(() => {
        dividerCls = cn(dividerClass, className)
    })

</script>

<div class={ dividerCls }>
    {@render children?.()}
</div>

<!--@component
    Generated by SvelteForge🔥
-->

