<script lang="ts">

    // --- Logic ---
    import { cn } from '@lib/utils';
    import type { DividerProps } from ".."
    
    let {
        children,
        class: className,
        dividerClass = $bindable(''),
        ...rest
    }: DividerProps = $props();


    // Setup Divider's class
    let dividerCls = $state(cn(dividerClass, className));
    $effect(() => {
        dividerCls = cn(dividerClass, className)
    })

</script>

<hr class={dividerCls} {...rest}/>
<!--@component
    Generated by SvelteForge🔥
-->

