<script lang="ts">

    // --- Logic ---
    import { cn } from '@lib/utils';
    import type { ButtonProps } from ".."
    
    let {
        children,
        class: className,
        buttonClass = $bindable('')
    }: ButtonProps = $props();


    // Setup Button's class
    let buttonCls = $state(cn(buttonClass, className));
    $effect(() => {
        buttonCls = cn(buttonClass, className)
    })

</script>

<div class={ buttonCls }>
    {@render children?.()}
</div>

<!--@component
    Generated by SvelteForge🔥
-->

