<script lang="ts">

    // --- Logic ---
    import { cn } from '@lib/utils';
    import type { Props } from ".."
    
    let {
        children,
        class: className,
        dropdownClass = $bindable('')
    }: Props = $props();


    // Setup Dropdown's class
    let dropdownCls = $state(cn(dropdownClass, className));
    $effect(() => {
        dropdownCls = cn(dropdownClass, className)
    })

</script>

<div class={ dropdownCls }>
    {@render children?.()}
</div>

<!--@component
    Generated by SvelteForge🔥
-->

