<script lang="ts">

    
    // --- Logic ---
    import { cn } from '@lib/utils';
    import type { TriggerProps } from ".."
	import { onMount } from 'svelte';
	import { getDropdownCtx } from '../ctx.svelte';
    
    let {
        children,
        class: className,
        triggerClass = $bindable('')
    }: TriggerProps = $props();

    // --- References ---
    let trigger_reference: HTMLDivElement | undefined = $state<HTMLDivElement | undefined>(undefined); 

    // --- Context ---
    const { _state, toggle, set } = getDropdownCtx()



    // Setup Trigger's class
    let triggerCls = $state(cn(triggerClass, className));
    $effect(() => {
        triggerCls = cn(triggerClass, className)
    })

    function toggle_menu() {
        // Toggle State
        console.log("Should be toggling state")
        console.log(_state.active)
        toggle();
    }

    function click_outside(event: MouseEvent) {
        
        // Use also trigger_reference
        const menu_ref = _state.content_reference
        const trigger_ref = trigger_reference

        if (
            menu_ref &&
            trigger_ref &&
            !menu_ref.contains(event.target as Node) &&
            !trigger_ref.contains(event.target as Node)
        ) {
            set(false); // Close dropdown
        }

    }

    onMount(() => {
        document.addEventListener("click", click_outside)
        return () => {
            document.removeEventListener("click", click_outside)
        }
    })

</script>

<!-- svelte-ignore a11y_no_static_element_interactions -->
<!-- svelte-ignore a11y_click_events_have_key_events -->
<div bind:this={trigger_reference} class={ triggerCls } onclick={toggle_menu}>
    {@render children?.()}
</div>

<!--@component
    Generated by SvelteForge🔥
-->

