<script lang="ts">

    // --- Logic ---
    import { cn } from '@lib/utils';
    import type { ContentProps } from ".."
	import { getDropdownCtx } from '../ctx.svelte';
    
    let {
        children,
        class: className,
        contentClass = $bindable('flex flex-col gap-2 border-box pt-4'),
        ...rest
    }: ContentProps = $props();

    // --- Context ---
    const { _state } = getDropdownCtx();

    // Setup Content's class
    let contentCls = $state(cn(contentClass, className));
    $effect(() => {
        contentCls = cn(contentClass, className)
    })

</script>

{#if _state.active}
    <div bind:this={_state.content_reference} class={ contentCls } {...rest}>
        {@render children?.()}
    </div>
{/if}

<!--@component
    Generated by SvelteForge🔥
-->

