"""
Directly adds the domain specified to hosts
"""

import sys
sys.dont_write_bytecode = True

import re
import os
import yaml
from pathlib import Path

is_root = os.geteuid() == 0

if not is_root:
    raise PermissionError("Requires sudo to run")

root: Path = Path(__file__).parent.parent
hosts_file = Path("/etc/hosts")
config: dict = yaml.load((root / 'config.yml').read_text(), Loader=yaml.FullLoader)
app_domain: str = config["app_domain"]
hosts_data = hosts_file.read_text()

pattern = re.compile(rf"^\s*127\.0\.0\.1\s+.*\b{re.escape(app_domain)}\b", re.MULTILINE)
match = pattern.search(hosts_data)
if pattern.search(hosts_data) is not None:
    print("Host already exists", match.group(0), sep="\n")
    sys.exit(0)
    
with hosts_file.open("a+") as f:
    f.write("\n\n")
    f.write(f"# Generated By register_domain.py\n")
    f.write(f"127.0.0.1 {app_domain}\n")
    f.write(f"127.0.0.1 api.{app_domain}\n")
    f.write("\n")

print("Updated hosts file")